### ISSUE TITLE
Add required quota to presenter resources

### ISSUE THREAD

**Issue by revodavid** [microsoft/aitour-e2e-dev-with-prompty-and-ai-studio#20]
Please add a section Required Quota to README.md in the Session Delivery folder. This should give any required information about the quota required to be available in a new tenant to set up the resources needed for session delivery.

**Comment by BethanyJep** [comment]
Section [updated](https://github.com/microsoft/aitour-e2e-dev-with-prompty-and-ai-studio/commit/1bbf3236ff318584697038a0ae853b7807901599)
